# Generated by Django 4.2.12 on 2026-06-17 07:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('COORDINATOR', 'Coordinator'), ('STATE_HEAD', 'State Head'), ('GCC_NOIDA', 'GCC Noida Team'), ('SUPER_ADMIN', 'Super Admin')], default='COORDINATOR', max_length=20, verbose_name='Role')),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Employee Code')),
                ('state', models.CharField(blank=True, help_text='Applicable for State Heads and Coordinators', max_length=50, null=True, verbose_name='State')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255, verbose_name='Applicant Name')),
                ('applicant_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('applicant_phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhaar Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Pincode')),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan'), ('EDUCATION', 'Education Loan'), ('BUSINESS', 'Business Loan'), ('AGRICULTURE', 'Agriculture Loan')], default='PERSONAL', max_length=20, verbose_name='Loan Type')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loan Amount')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Purpose')),
                ('tenure_months', models.PositiveIntegerField(verbose_name='Tenure (Months)')),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Income')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('STATE_REVIEW', 'State Review'), ('GCC_REVIEW', 'GCC Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('application_id', models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='Application ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('INCOME_PROOF', 'Income Proof'), ('BANK_STATEMENT', 'Bank Statement'), ('PROPERTY', 'Property Document'), ('PHOTO', 'Photograph'), ('SIGNATURE', 'Signature'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='uploads/documents/%Y/%m/', verbose_name='File')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Filename')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication', verbose_name='Application')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Document Upload',
                'verbose_name_plural': 'Document Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('STATE_REVIEW', 'State Review'), ('GCC_REVIEW', 'GCC Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], max_length=20, null=True, verbose_name='From Status')),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('STATE_REVIEW', 'State Review'), ('GCC_REVIEW', 'GCC Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], max_length=20, verbose_name='To Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='loans.loanapplication', verbose_name='Application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
            ],
            options={
                'verbose_name': 'Application History',
                'verbose_name_plural': 'Application Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
