# Generated by Django 4.2.12 on 2026-06-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='existing_loan',
            field=models.BooleanField(default=False, verbose_name='Existing Loan'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
