# Generated by Django 4.2.12 on 2026-06-17 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationhistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('STATE_REVIEW', 'Under State Review'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('RESUBMITTED', 'Resubmitted'), ('GCC_REVIEW', 'Under GCC Review'), ('ADDITIONAL_DOCS_REQUIRED', 'Additional Documents Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], max_length=30, null=True, verbose_name='From Status'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('STATE_REVIEW', 'Under State Review'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('RESUBMITTED', 'Resubmitted'), ('GCC_REVIEW', 'Under GCC Review'), ('ADDITIONAL_DOCS_REQUIRED', 'Additional Documents Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], max_length=30, verbose_name='To Status'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('STATE_REVIEW', 'Under State Review'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('RESUBMITTED', 'Resubmitted'), ('GCC_REVIEW', 'Under GCC Review'), ('ADDITIONAL_DOCS_REQUIRED', 'Additional Documents Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='DRAFT', max_length=30, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_APPLICATION', 'Create Application'), ('UPDATE_STATUS', 'Update Status'), ('UPLOAD_DOCUMENT', 'Upload Document'), ('ADD_REMARK', 'Add Remark'), ('CREATE_USER', 'Create User'), ('EDIT_USER', 'Edit User'), ('RESET_PASSWORD', 'Reset Password'), ('TOGGLE_USER', 'Toggle User Active')], max_length=30, verbose_name='Action')),
                ('module', models.CharField(blank=True, max_length=50, verbose_name='Module')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
