# Generated by Django 4.2.12 on 2026-06-19 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_documentupload_verification_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_APPLICATION', 'Create Application'), ('UPDATE_STATUS', 'Update Status'), ('UPLOAD_DOCUMENT', 'Upload Document'), ('ADD_REMARK', 'Add Remark'), ('CREATE_USER', 'Create User'), ('EDIT_USER', 'Edit User'), ('RESET_PASSWORD', 'Reset Password'), ('TOGGLE_USER', 'Toggle User Active'), ('VERIFY_DOCUMENT', 'Verify Document')], max_length=30, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('APPLICATION_ASSIGNED', 'Application Assigned'), ('SYSTEM_ALERT', 'System Alert')], default='STATUS_CHANGE', max_length=25, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='loans.loanapplication', verbose_name='Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
