# Generated by Django 4.2.12 on 2026-06-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invitation Sent At'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVATED', 'Activated'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='Invitation Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Invitation Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Created At'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Password Set At'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_APPLICATION', 'Create Application'), ('UPDATE_STATUS', 'Update Status'), ('UPLOAD_DOCUMENT', 'Upload Document'), ('ADD_REMARK', 'Add Remark'), ('CREATE_USER', 'Create User'), ('EDIT_USER', 'Edit User'), ('RESET_PASSWORD', 'Reset Password'), ('TOGGLE_USER', 'Toggle User Active'), ('VERIFY_DOCUMENT', 'Verify Document'), ('SEND_INVITATION', 'Send Invitation'), ('RESEND_INVITATION', 'Resend Invitation'), ('ACCOUNT_ACTIVATED', 'Account Activated')], max_length=30, verbose_name='Action'),
        ),
    ]
