# Generated by Django 4.2.12 on 2026-06-23 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Activity At'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='last_activity_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_last_activity', to=settings.AUTH_USER_MODEL, verbose_name='Last Activity By'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status'], name='loans_loana_status_ff4c26_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['assigned_to'], name='loans_loana_assigne_49f97e_idx'),
        ),
    ]
